### ISSUE TITLE
I could not access the stream with the headers provided in the readme 

### ISSUE THREAD

**Issue by ravi3177** [SabBits/hls-proxifier#2]
![image](https://github.com/SabBits/hls-proxifier/assets/79292977/625fc17e-6b7f-4429-9d7a-b09d3afe85fb)
   http://localhost:5000/proxify?url=https://cph-msl.akamaized.net/hls/live/2000341/test/master.m3u8
   http://127.0.0.1:5000/proxify?url=https://65xl.short.gy/Telegram@M3UIndia-TataPlay.m3u
   when using this url a file named proxify without any filename extension is download and no use of it.
   I have tried various url,so I kindly request that can you upload a video or document on how to access the m3u url using this localhost application

**Comment by SabBits** [comment]
The first link you provided (http://localhost:5000/proxify?url=https://cph-msl.akamaized.net/hls/live/2000341/test/master.m3u8) seems to work fine for me :) 

You just have to paste the link into your player, and it should start playing.
![image](https://github.com/SabBits/hls-proxifier/assets/77656281/92c5aa84-81f4-4fbe-8f08-f23bf626872e)

As for the second link, it's an M3U, not a single stream, so that's not going to work.

And yes, I'm working on the documentation for this; this project still has a long way to go. I will also create a video guide to demonstrate the entire process.
